version: '2'
services:

  app:
    build: .
    ports:
    - "8006"
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.0.16:5432/mydb
    - SPRING_KAFKA_PRODUCER_BOOTSTRAP-SERVER=192.168.0.16:9092


